services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
volumes:
  mariadb_data:
