@baseUrl = https://organic-eureka-695w649q7gpxh56jw-3001.app.github.dev
### Teste: Login
POST https://organic-eureka-695w649q7gpxh56jw-3001.app.github.dev/api/auth/login
Content-Type: application/json

{
    "email": "teste@teste.com",
    "senha": "123456"
}


###

### Teste: Criar Usuário
POST https://organic-eureka-695w649q7gpxh56jw-3001.app.github.dev/api/auth/cru
Content-Type: application/json

{
    "nome": "Usuário Teste",
    "email": "teste@teste.com",
    "senha": "123456"
}

###

### Teste: Criar Tarefa
POST https://organic-eureka-695w649q7gpxh56jw-3001.app.github.dev/api/auth/createtask
Content-Type: application/json

{
    "texto": "Minha nova tarefa"
}

###

### Teste: Buscar Tarefas
GET https://organic-eureka-695w649q7gpxh56jw-3001.app.github.dev/api/auth/gettasks
Content-Type: application/json

###

### Teste: Deletar Tarefa
DELETE https://organic-eureka-695w649q7gpxh56jw-3001.app.github.dev/api/auth/deletetask/Minha%20nova%20tarefa
Content-Type: application/json

###